language: go
sudo: required
services:
  - docker
go: 
  - "1.10.x"
script:
  - echo "GETTING TO COMMAND **"
  - docker images
  - git submodule update --init
  - which make
  - go get github.com/cpuguy83/go-md2man
  - make build TARGET=centos7 VERSIONS=8
  - docker images
  - echo "for subdir in `find . -type d` 
do
if [ -f ./$subdir/layer.tar ]   
then   
        echo "extracting"; echo $subdir
        tar xvf ./$subdir/layer.tar -C ./$subdir 
#       echo Yes;echo $subdir
 else 
         echo "not";echo $subdir
 fi 
 done" > test.sh
  -  sh test.sh
  - find . -name package.json -print
