language: go
sudo: required
services:
  - docker
go: 
  - "1.10.x"
script:
  - echo "GETTING TO COMMAND **"
  - docker images
  - git submodule update --init
  - which make
  - go get github.com/cpuguy83/go-md2man
  - make build TARGET=centos7 VERSIONS=8
  - docker images
  - mkdir extract; cd extract
  - docker save > test.tar
  - tar xvf test.tar
  - sh ../test.sh
  - find . -name package.json -print

