language: go
go: 
  - "1.10.x"
script:
  - echo "GETTING TO COMMAND **"
  - git submodule update --init
  - which make
  - go get github.com/cpuguy83/go-md2man
  - make build TARGET=centos7 VERSIONS=8
